import Vue from 'vue'

Vue.component('app-main-pc', () => import('./main-pc'))
Vue.component('app-register', () => import('./register'))
Vue.component('app-button', () => import('./button'))
Vue.component('app-download', () => import('./download'))
Vue.component('app-footer', () => import('./footer'))
Vue.component('app-button-icon', () => import('./button-icon'))
Vue.component('app-brand-item', () => import('./brand-item'))
Vue.component('app-popover', () => import('./popover'))
Vue.component('app-popover-medias', () => import('./popover-medias'))
Vue.component('app-footer-info', () => import('./footer-info'))
Vue.component('app-logo', () => import('./logo'))
Vue.component('app-main-touch', () => import('./main-touch'))
Vue.component('app-button-touch', () => import('./button-touch'))
Vue.component('app-banner', () => import('./banner'))
Vue.component('app-banner-pc', () => import('./banner-pc'))
